[package]
name = "verify_token_with_some_key"
version = "0.1.1"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.5", default-features = false, features = ['std'] }
jwt-core = { path = "../../core/" }
serde_json = "1.0.149"
chrono = "0.4.44"
